spring.application.name=petcare-be

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=baolgpc08011@fpt.edu.vn
spring.mail.password=ubnoivoqlgkbaej
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# C?u h�nh k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/petcare?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=sa
spring.datasource.password=123123
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# C?u h�nh driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) c?u h�nh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Hi?n th? c�u SQL trong console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.web.resources.add-mappings=true

# Key AI
gemini.api.key=AIzaSyD9O2X5xmIpB8as6vT5aeZIS5fJ0Jvdsxg


logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG